### ISSUE TITLE
HeisenbergLinearStructure.linkTo() completion block ideas

### ISSUE THREAD

**Issue by neoneye** [eliakorkmaz/Heisenberg#2]
Currently the completionblock is required. But in the example code, I see it being mostly an empty block.

Maybe make it non-optional. Or remove it.

Or move it to a function like this:

```
func run(_ completion: @escaping (_ val: HeisenbergLinearStructure<Value>) -> ()) -> Self {
    completion(self)
    return self
}
```

Or have example code that shows how to use the completion block.

**Comment by eliakorkmaz** [comment]
Closed all issues with Heisenberg 0.1.1 version. You made a huge code-review for the library. I am greatful for this, thank you 🙌
